version: '3.1'
services:
  database:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_users
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 12345678

